//
//  SFSymbol.swift
//  NMASFSymbol
//
//  Created by Monica Rondón on 2/1/22.
//

import Foundation

// MARK: - SFSymbol
public enum SFSymbol: Int, CaseIterable {

    case square_and_arrow_up
    case square_and_arrow_up_fill
    case square_and_arrow_up_circle
    case square_and_arrow_up_circle_fill
    case square_and_arrow_up_trianglebadge_exclamationmark
    case square_and_arrow_down
    case square_and_arrow_down_fill
    case square_and_arrow_up_on_square
    case square_and_arrow_up_on_square_fill
    case square_and_arrow_down_on_square
    case square_and_arrow_down_on_square_fill
    case rectangle_portrait_and_arrow_right
    case rectangle_portrait_and_arrow_right_fill
    case pencil
    case pencil_circle
    case pencil_circle_fill
    case pencil_slash
    case square_and_pencil
    case rectangle_and_pencil_and_ellipsis
    case scribble
    case scribble_variable
    case highlighter
    case pencil_and_outline
    case pencil_tip
    case pencil_tip_crop_circle
    case pencil_tip_crop_circle_badge_plus
    case pencil_tip_crop_circle_badge_minus
    case pencil_tip_crop_circle_badge_arrow_forward
    case lasso
    case lasso_and_sparkles
    case trash
    case trash_fill
    case trash_circle
    case trash_circle_fill
    case trash_square
    case trash_square_fill
    case trash_slash
    case trash_slash_fill
    case trash_slash_circle
    case trash_slash_circle_fill
    case trash_slash_square
    case trash_slash_square_fill
    case folder
    case folder_fill
    case folder_circle
    case folder_circle_fill
    case folder_badge_plus
    case folder_fill_badge_plus
    case folder_badge_minus
    case folder_fill_badge_minus
    case folder_badge_questionmark
    case folder_fill_badge_questionmark
    case folder_badge_person_crop
    case folder_fill_badge_person_crop
    case square_grid_3x1_folder_badge_plus
    case square_grid_3x1_folder_fill_badge_plus
    case folder_badge_gearshape
    case folder_fill_badge_gearshape
    case plus_rectangle_on_folder
    case plus_rectangle_on_folder_fill
    case questionmark_folder
    case questionmark_folder_fill
    case paperplane
    case paperplane_fill
    case paperplane_circle
    case paperplane_circle_fill
    case tray
    case tray_fill
    case tray_circle
    case tray_circle_fill
    case tray_and_arrow_up
    case tray_and_arrow_up_fill
    case tray_and_arrow_down
    case tray_and_arrow_down_fill
    case tray_2
    case tray_2_fill
    case tray_full
    case tray_full_fill
    case externaldrive
    case externaldrive_fill
    case externaldrive_badge_plus
    case externaldrive_fill_badge_plus
    case externaldrive_badge_minus
    case externaldrive_fill_badge_minus
    case externaldrive_badge_checkmark
    case externaldrive_fill_badge_checkmark
    case externaldrive_badge_xmark
    case externaldrive_fill_badge_xmark
    case externaldrive_badge_person_crop
    case externaldrive_fill_badge_person_crop
    case externaldrive_badge_icloud
    case externaldrive_fill_badge_icloud
    case externaldrive_badge_wifi
    case externaldrive_fill_badge_wifi
    case externaldrive_badge_timemachine
    case externaldrive_fill_badge_timemachine
    case internaldrive
    case internaldrive_fill
    case opticaldiscdrive
    case opticaldiscdrive_fill
    case externaldrive_connected_to_line_below
    case externaldrive_connected_to_line_below_fill
    case archivebox
    case archivebox_fill
    case archivebox_circle
    case archivebox_circle_fill
    case xmark_bin
    case xmark_bin_fill
    case xmark_bin_circle
    case xmark_bin_circle_fill
    case arrow_up_bin
    case arrow_up_bin_fill
    case doc
    case doc_fill
    case doc_circle
    case doc_circle_fill
    case doc_badge_plus
    case doc_fill_badge_plus
    case doc_badge_gearshape
    case doc_badge_gearshape_fill
    case doc_badge_ellipsis
    case doc_fill_badge_ellipsis
    case lock_doc
    case lock_doc_fill
    case arrow_up_doc
    case arrow_up_doc_fill
    case arrow_down_doc
    case arrow_down_doc_fill
    case doc_text
    case doc_text_fill
    case doc_zipper
    case doc_on_doc
    case doc_on_doc_fill
    case doc_on_clipboard
    case arrow_right_doc_on_clipboard
    case arrow_up_doc_on_clipboard
    case arrow_triangle_2_circlepath_doc_on_clipboard
    case doc_on_clipboard_fill
    case doc_richtext
    case doc_richtext_fill
    case doc_plaintext
    case doc_plaintext_fill
    case doc_append
    case doc_append_fill
    case doc_text_below_ecg
    case doc_text_below_ecg_fill
    case chart_bar_doc_horizontal
    case chart_bar_doc_horizontal_fill
    case list_bullet_rectangle_portrait
    case list_bullet_rectangle_portrait_fill
    case doc_text_magnifyingglass
    case list_bullet_rectangle
    case list_bullet_rectangle_fill
    case list_dash_header_rectangle
    case terminal
    case terminal_fill
    case note
    case note_text
    case note_text_badge_plus
    case calendar
    case calendar_circle
    case calendar_circle_fill
    case calendar_badge_plus
    case calendar_badge_minus
    case calendar_badge_clock
    case calendar_badge_exclamationmark
    case calendar_day_timeline_left
    case calendar_day_timeline_right
    case calendar_day_timeline_leading
    case calendar_day_timeline_trailing
    case arrowshape_turn_up_left
    case arrowshape_turn_up_left_fill
    case arrowshape_turn_up_left_circle
    case arrowshape_turn_up_left_circle_fill
    case arrowshape_turn_up_backward
    case arrowshape_turn_up_backward_fill
    case arrowshape_turn_up_backward_circle
    case arrowshape_turn_up_backward_circle_fill
    case arrowshape_turn_up_right
    case arrowshape_turn_up_right_fill
    case arrowshape_turn_up_right_circle
    case arrowshape_turn_up_right_circle_fill
    case arrowshape_turn_up_forward
    case arrowshape_turn_up_forward_fill
    case arrowshape_turn_up_forward_circle
    case arrowshape_turn_up_forward_circle_fill
    case arrowshape_turn_up_left_2
    case arrowshape_turn_up_left_2_fill
    case arrowshape_turn_up_left_2_circle
    case arrowshape_turn_up_left_2_circle_fill
    case arrowshape_turn_up_backward_2
    case arrowshape_turn_up_backward_2_fill
    case arrowshape_turn_up_backward_2_circle
    case arrowshape_turn_up_backward_2_circle_fill
    case arrowshape_zigzag_right
    case arrowshape_zigzag_right_fill
    case arrowshape_zigzag_forward
    case arrowshape_zigzag_forward_fill
    case arrowshape_bounce_right
    case arrowshape_bounce_right_fill
    case arrowshape_bounce_forward
    case arrowshape_bounce_forward_fill
    case book
    case book_fill
    case book_circle
    case book_circle_fill
    case books_vertical
    case books_vertical_fill
    case books_vertical_circle
    case books_vertical_circle_fill
    case book_closed
    case book_closed_fill
    case book_closed_circle
    case book_closed_circle_fill
    case character_book_closed
    case character_book_closed_fill
    case text_book_closed
    case text_book_closed_fill
    case menucard
    case menucard_fill
    case greetingcard
    case greetingcard_fill
    case magazine
    case magazine_fill
    case newspaper
    case newspaper_fill
    case newspaper_circle
    case newspaper_circle_fill
    case heart_text_square
    case heart_text_square_fill
    case square_text_square
    case square_text_square_fill
    case doc_text_image
    case doc_text_image_fill
    case bookmark
    case bookmark_fill
    case bookmark_circle
    case bookmark_circle_fill
    case bookmark_square
    case bookmark_square_fill
    case bookmark_slash
    case bookmark_slash_fill
    case rosette
    case graduationcap
    case graduationcap_fill
    case graduationcap_circle
    case graduationcap_circle_fill
    case ticket
    case ticket_fill
    case paperclip
    case paperclip_circle
    case paperclip_circle_fill
    case paperclip_badge_ellipsis
    case rectangle_and_paperclip
    case rectangle_dashed_and_paperclip
    case link
    case link_circle
    case link_circle_fill
    case link_badge_plus
    case personalhotspot
    case personalhotspot_circle
    case personalhotspot_circle_fill
    case lineweight
    case person
    case person_fill
    case person_fill_turn_right
    case person_fill_turn_down
    case person_fill_turn_left
    case person_fill_checkmark
    case person_fill_xmark
    case person_fill_questionmark
    case person_circle
    case person_circle_fill
    case person_badge_plus
    case person_fill_badge_plus
    case person_badge_minus
    case person_fill_badge_minus
    case person_badge_clock
    case person_badge_clock_fill
    case shareplay
    case shareplay_slash
    case rectangle_inset_filled_and_person_filled
    case person_and_arrow_left_and_arrow_right
    case person_fill_and_arrow_left_and_arrow_right
    case person_2
    case person_2_fill
    case person_2_circle
    case person_2_circle_fill
    case person_wave_2
    case person_wave_2_fill
    case person_2_wave_2
    case person_2_wave_2_fill
    case person_3
    case person_3_fill
    case person_3_sequence
    case person_3_sequence_fill
    case lanyardcard
    case lanyardcard_fill
    case person_crop_circle
    case person_crop_circle_fill
    case person_crop_circle_badge_plus
    case person_crop_circle_fill_badge_plus
    case person_crop_circle_badge_minus
    case person_crop_circle_fill_badge_minus
    case person_crop_circle_badge_checkmark
    case person_crop_circle_fill_badge_checkmark
    case person_crop_circle_badge_xmark
    case person_crop_circle_fill_badge_xmark
    case person_crop_circle_badge_questionmark
    case person_crop_circle_badge_questionmark_fill
    case person_crop_circle_badge_exclamationmark
    case person_crop_circle_badge_exclamationmark_fill
    case person_crop_circle_badge_moon
    case person_crop_circle_badge_moon_fill
    case person_crop_circle_badge_clock
    case person_crop_circle_badge_clock_fill
    case person_crop_circle_badge
    case person_crop_circle_badge_fill
    case person_crop_square
    case person_crop_square_fill
    case person_crop_artframe
    case photo_artframe
    case person_crop_rectangle_stack
    case person_crop_rectangle_stack_fill
    case person_2_crop_square_stack
    case person_2_crop_square_stack_fill
    case person_crop_rectangle
    case person_crop_rectangle_fill
    case arrow_up_and_person_rectangle_portrait
    case arrow_up_and_person_rectangle_turn_right
    case arrow_up_and_person_rectangle_turn_left
    case person_crop_square_filled_and_at_rectangle
    case person_crop_square_filled_and_at_rectangle_fill
    case square_and_at_rectangle
    case square_and_at_rectangle_fill
    case person_text_rectangle
    case person_text_rectangle_fill
    case command_circle
    case command_circle_fill
    case command_square
    case command_square_fill
    case clear_fill
    case delete_left_fill
    case delete_backward
    case delete_backward_fill
    case delete_right_fill
    case delete_forward
    case delete_forward_fill
    case shift_fill
    case capslock_fill
    case restart
    case restart_circle
    case restart_circle_fill
    case sleep
    case sleep_circle
    case sleep_circle_fill
    case wake
    case wake_circle
    case wake_circle_fill
    case power_circle
    case power_circle_fill
    case power_dotted
    case alternatingcurrent
    case dot_arrowtriangles_up_right_down_left_circle
    case globe
    case globe_badge_chevron_backward
    case network
    case network_badge_shield_half_filled
    case globe_americas
    case globe_americas_fill
    case globe_europe_africa
    case globe_europe_africa_fill
    case globe_asia_australia
    case globe_asia_australia_fill
    case sun_min
    case sun_min_fill
    case sun_max
    case sun_max_fill
    case sun_max_circle
    case sun_max_circle_fill
    case sunrise
    case sunrise_fill
    case sunset
    case sunset_fill
    case sun_and_horizon
    case sun_and_horizon_fill
    case sun_dust
    case sun_dust_fill
    case sun_haze
    case sun_haze_fill
    case moon
    case moon_circle
    case moon_circle_fill
    case zzz
    case moon_zzz
    case moon_zzz_fill
    case sparkle
    case sparkles
    case moon_stars
    case moon_stars_fill
    case cloud
    case cloud_fill
    case cloud_drizzle
    case cloud_drizzle_fill
    case cloud_rain
    case cloud_rain_fill
    case cloud_heavyrain
    case cloud_heavyrain_fill
    case cloud_fog
    case cloud_fog_fill
    case cloud_hail
    case cloud_hail_fill
    case cloud_snow
    case cloud_snow_fill
    case cloud_sleet
    case cloud_sleet_fill
    case cloud_bolt
    case cloud_bolt_fill
    case cloud_bolt_rain
    case cloud_bolt_rain_fill
    case cloud_sun
    case cloud_sun_fill
    case cloud_sun_rain
    case cloud_sun_rain_fill
    case cloud_sun_bolt
    case cloud_sun_bolt_fill
    case cloud_moon
    case cloud_moon_fill
    case cloud_moon_rain
    case cloud_moon_rain_fill
    case cloud_moon_bolt
    case cloud_moon_bolt_fill
    case smoke
    case smoke_fill
    case wind
    case wind_snow
    case snowflake_circle
    case snowflake_circle_fill
    case tornado
    case tropicalstorm
    case hurricane
    case thermometer_sun
    case thermometer_sun_fill
    case thermometer_snowflake
    case thermometer
    case aqi_low
    case aqi_medium
    case aqi_high
    case humidity
    case humidity_fill
    case umbrella
    case flame
    case flame_fill
    case flame_circle
    case flame_circle_fill
    case light_min
    case light_max
    case rays
    case slowmo
    case timelapse
    case cursorarrow_rays
    case cursorarrow
    case cursorarrow_square
    case cursorarrow_and_square_on_square_dashed
    case cursorarrow_click
    case cursorarrow_click_2
    case contextualmenu_and_cursorarrow
    case filemenu_and_cursorarrow
    case filemenu_and_selection
    case dot_circle_and_hand_point_up_left_fill
    case dot_circle_and_cursorarrow
    case cursorarrow_motionlines
    case cursorarrow_motionlines_click
    case cursorarrow_click_badge_clock
    case keyboard
    case keyboard_fill
    case keyboard_badge_ellipsis
    case keyboard_chevron_compact_down
    case keyboard_chevron_compact_left
    case keyboard_onehanded_left
    case keyboard_onehanded_right
    case rectangle_3_group
    case rectangle_3_group_fill
    case square_grid_3x2
    case square_grid_3x2_fill
    case rectangle_grid_3x2
    case rectangle_grid_3x2_fill
    case square_grid_2x2
    case square_grid_2x2_fill
    case rectangle_grid_2x2
    case rectangle_grid_2x2_fill
    case square_grid_3x1_below_line_grid_1x2
    case square_grid_3x1_below_line_grid_1x2_fill
    case square_grid_4x3_fill
    case rectangle_grid_1x2
    case rectangle_grid_1x2_fill
    case circle_grid_2x2
    case circle_grid_2x2_fill
    case circle_grid_3x3
    case circle_grid_3x3_fill
    case circle_grid_3x3_circle
    case circle_grid_3x3_circle_fill
    case square_grid_3x3
    case square_grid_3x3_fill
    case square_grid_3x3_topleft_filled
    case square_grid_3x3_topmiddle_filled
    case square_grid_3x3_topright_filled
    case square_grid_3x3_middleleft_filled
    case square_grid_3x3_middle_filled
    case square_grid_3x3_middleright_filled
    case square_grid_3x3_bottomleft_filled
    case square_grid_3x3_bottommiddle_filled
    case square_grid_3x3_bottomright_filled
    case circle_hexagongrid
    case circle_hexagongrid_fill
    case circle_hexagongrid_circle
    case circle_hexagongrid_circle_fill
    case circle_hexagonpath
    case circle_hexagonpath_fill
    case circle_grid_cross
    case circle_grid_cross_fill
    case circle_grid_cross_left_filled
    case circle_grid_cross_up_filled
    case circle_grid_cross_right_filled
    case circle_grid_cross_down_filled
    case seal
    case seal_fill
    case checkmark_seal
    case checkmark_seal_fill
    case xmark_seal
    case xmark_seal_fill
    case exclamationmark_triangle_fill
    case drop
    case drop_fill
    case drop_circle
    case drop_circle_fill
    case drop_triangle
    case drop_triangle_fill
    case play
    case play_fill
    case play_circle
    case play_circle_fill
    case play_square
    case play_square_fill
    case play_rectangle
    case play_rectangle_fill
    case play_slash
    case play_slash_fill
    case pause
    case pause_fill
    case pause_circle
    case pause_circle_fill
    case pause_rectangle
    case pause_rectangle_fill
    case stop
    case stop_fill
    case stop_circle
    case stop_circle_fill
    case record_circle
    case record_circle_fill
    case playpause
    case playpause_fill
    case backward
    case backward_fill
    case backward_circle
    case backward_circle_fill
    case forward
    case forward_fill
    case forward_circle
    case forward_circle_fill
    case backward_end
    case backward_end_fill
    case forward_end
    case forward_end_fill
    case backward_end_alt
    case backward_end_alt_fill
    case forward_end_alt
    case forward_end_alt_fill
    case backward_frame
    case backward_frame_fill
    case forward_frame
    case forward_frame_fill
    case eject_fill
    case eject_circle
    case eject_circle_fill
    case mount
    case mount_fill
    case memories
    case memories_badge_plus
    case memories_badge_minus
    case shuffle
    case shuffle_circle
    case shuffle_circle_fill
    case `repeat`
    case repeat_circle
    case repeat_circle_fill
    case repeat_1
    case repeat_1_circle
    case repeat_1_circle_fill
    case infinity
    case infinity_circle
    case infinity_circle_fill
    case megaphone
    case megaphone_fill
    case speaker
    case speaker_fill
    case speaker_circle
    case speaker_circle_fill
    case speaker_slash
    case speaker_slash_fill
    case speaker_slash_circle
    case speaker_slash_circle_fill
    case speaker_zzz
    case speaker_zzz_fill
    case speaker_wave_1
    case speaker_wave_1_fill
    case speaker_wave_2
    case speaker_wave_2_fill
    case speaker_wave_2_circle
    case speaker_wave_2_circle_fill
    case speaker_wave_3
    case speaker_wave_3_fill
    case speaker_badge_exclamationmark
    case speaker_badge_exclamationmark_fill
    case badge_plus_radiowaves_right
    case badge_plus_radiowaves_forward
    case music_note
    case music_note_list
    case music_quarternote_3
    case music_mic
    case music_mic_circle
    case music_mic_circle_fill
    case arrow_rectanglepath
    case goforward
    case gobackward
    case goforward_5
    case gobackward_5
    case goforward_10
    case gobackward_10
    case goforward_15
    case gobackward_15
    case goforward_30
    case gobackward_30
    case goforward_45
    case gobackward_45
    case goforward_60
    case gobackward_60
    case goforward_75
    case gobackward_75
    case goforward_90
    case gobackward_90
    case goforward_plus
    case gobackward_minus
    case swift
    case magnifyingglass
    case magnifyingglass_circle
    case magnifyingglass_circle_fill
    case plus_magnifyingglass
    case minus_magnifyingglass
    case _1_magnifyingglass
    case arrow_up_left_and_down_right_magnifyingglass
    case text_magnifyingglass
    case sparkle_magnifyingglass
    case location_magnifyingglass
    case loupe
    case mic
    case mic_fill
    case mic_circle
    case mic_circle_fill
    case mic_square
    case mic_square_fill
    case mic_slash
    case mic_slash_fill
    case mic_slash_circle
    case mic_slash_circle_fill
    case mic_badge_plus
    case mic_fill_badge_plus
    case line_diagonal
    case line_diagonal_arrow
    case circle_slash
    case circle_slash_fill
    case smallcircle_filled_circle_fill
    case circle_dashed
    case circle_dashed_inset_filled
    case circle_dotted
    case circlebadge
    case circlebadge_fill
    case circlebadge_2
    case circlebadge_2_fill
    case smallcircle_circle_fill
    case target
    case capsule
    case capsule_fill
    case capsule_lefthalf_filled
    case capsule_righthalf_filled
    case capsule_tophalf_filled
    case capsule_bottomhalf_filled
    case capsule_inset_filled
    case capsule_portrait
    case capsule_portrait_fill
    case capsule_portrait_lefthalf_filled
    case capsule_portrait_righthalf_filled
    case capsule_portrait_tophalf_filled
    case capsule_portrait_bottomhalf_filled
    case capsule_portrait_inset_filled
    case oval
    case oval_fill
    case oval_lefthalf_filled
    case oval_righthalf_filled
    case oval_tophalf_filled
    case oval_bottomhalf_filled
    case oval_inset_filled
    case oval_portrait
    case oval_portrait_fill
    case oval_portrait_lefthalf_filled
    case oval_portrait_righthalf_filled
    case oval_portrait_tophalf_filled
    case oval_portrait_bottomhalf_filled
    case oval_portrait_inset_filled
    case square_slash
    case square_slash_fill
    case square_inset_filled
    case square_split_2x1
    case square_split_2x1_fill
    case square_split_1x2_fill
    case square_split_2x2_fill
    case square_split_diagonal_2x2_fill
    case square_split_diagonal
    case square_split_diagonal_fill
    case dot_square_fill
    case circle_square
    case circle_square_fill
    case square_dashed
    case square_dashed_inset_filled
    case plus_square_dashed
    case questionmark_square_dashed
    case square_on_square
    case square_fill_on_square_fill
    case square_filled_on_square
    case hand_raised_square_on_square
    case hand_raised_square_on_square_fill
    case sparkles_square_filled_on_square
    case square_on_square_dashed
    case plus_square_on_square
    case plus_square_fill_on_square_fill
    case square_on_circle
    case square_fill_on_circle_fill
    case r_square_on_square
    case r_square_on_square_fill
    case j_square_on_square
    case j_square_on_square_fill
    case h_square_on_square
    case h_square_on_square_fill
    case square_stack
    case square_stack_fill
    case squareshape
    case squareshape_fill
    case squareshape_dashed_squareshape
    case squareshape_squareshape_dashed
    case dot_squareshape
    case dot_squareshape_fill
    case app
    case app_fill
    case rectangle
    case rectangle_fill
    case rectangle_slash
    case rectangle_slash_fill
    case rectangle_lefthalf_filled
    case rectangle_righthalf_filled
    case rectangle_leadinghalf_filled
    case rectangle_trailinghalf_filled
    case rectangle_tophalf_filled
    case rectangle_bottomhalf_filled
    case rectangle_split_2x1
    case rectangle_split_2x1_fill
    case rectangle_split_2x1_slash
    case rectangle_split_2x1_slash_fill
    case rectangle_split_1x2
    case rectangle_split_1x2_fill
    case rectangle_split_3x1
    case rectangle_split_3x1_fill
    case rectangle_split_2x2
    case rectangle_split_2x2_fill
    case tablecells
    case tablecells_fill
    case tablecells_badge_ellipsis
    case tablecells_fill_badge_ellipsis
    case rectangle_split_3x3
    case rectangle_inset_filled
    case rectangle_tophalf_inset_filled
    case rectangle_bottomhalf_inset_filled
    case rectangle_lefthalf_inset_filled
    case rectangle_righthalf_inset_filled
    case rectangle_leadinghalf_inset_filled
    case rectangle_trailinghalf_inset_filled
    case rectangle_lefthalf_inset_filled_arrow_left
    case rectangle_righthalf_inset_filled_arrow_right
    case rectangle_leadinghalf_inset_filled_arrow_leading
    case rectangle_trailinghalf_inset_filled_arrow_trailing
    case rectangle_topthird_inset_filled
    case rectangle_bottomthird_inset_filled
    case rectangle_leftthird_inset_filled
    case rectangle_rightthird_inset_filled
    case rectangle_leadingthird_inset_filled
    case rectangle_trailingthird_inset_filled
    case rectangle_center_inset_filled
    case rectangle_center_inset_filled_badge_plus
    case rectangle_inset_topleft_filled
    case rectangle_inset_topright_filled
    case rectangle_inset_topleading_filled
    case rectangle_inset_toptrailing_filled
    case rectangle_inset_bottomleft_filled
    case rectangle_inset_bottomright_filled
    case rectangle_inset_bottomleading_filled
    case rectangle_inset_bottomtrailing_filled
    case rectangle_on_rectangle
    case rectangle_fill_on_rectangle_fill
    case rectangle_on_rectangle_circle
    case rectangle_on_rectangle_circle_fill
    case rectangle_on_rectangle_square
    case rectangle_on_rectangle_square_fill
    case rectangle_inset_filled_on_rectangle
    case rectangle_on_rectangle_slash
    case rectangle_on_rectangle_slash_fill
    case rectangle_on_rectangle_slash_circle
    case rectangle_on_rectangle_slash_circle_fill
    case play_rectangle_on_rectangle
    case play_rectangle_on_rectangle_fill
    case play_rectangle_on_rectangle_circle
    case play_rectangle_on_rectangle_circle_fill
    case plus_rectangle_on_rectangle
    case plus_rectangle_fill_on_rectangle_fill
    case rectangle_portrait
    case rectangle_portrait_fill
    case rectangle_portrait_slash
    case rectangle_portrait_slash_fill
    case rectangle_portrait_lefthalf_filled
    case rectangle_portrait_righthalf_filled
    case rectangle_portrait_tophalf_filled
    case rectangle_portrait_bottomhalf_filled
    case rectangle_portrait_inset_filled
    case rectangle_portrait_tophalf_inset_filled
    case rectangle_portrait_bottomhalf_inset_filled
    case rectangle_portrait_lefthalf_inset_filled
    case rectangle_portrait_righthalf_inset_filled
    case rectangle_portrait_leadinghalf_inset_filled
    case rectangle_portrait_trailinghalf_inset_filled
    case rectangle_portrait_topthird_inset_filled
    case rectangle_portrait_bottomthird_inset_filled
    case rectangle_portrait_leftthird_inset_filled
    case rectangle_portrait_rightthird_inset_filled
    case rectangle_portrait_leadingthird_inset_filled
    case rectangle_portrait_trailingthird_inset_filled
    case rectangle_portrait_center_inset_filled
    case rectangle_portrait_topleft_inset_filled
    case rectangle_portrait_topright_inset_filled
    case rectangle_portrait_topleading_inset_filled
    case rectangle_portrait_toptrailing_inset_filled
    case rectangle_portrait_bottomleft_inset_filled
    case rectangle_portrait_bottomright_inset_filled
    case rectangle_portrait_bottomleading_inset_filled
    case rectangle_portrait_bottomtrailing_inset_filled
    case rectangle_portrait_on_rectangle_portrait
    case rectangle_portrait_on_rectangle_portrait_fill
    case rectangle_portrait_on_rectangle_portrait_slash
    case rectangle_portrait_on_rectangle_portrait_slash_fill
    case rectangle_portrait_split_2x1
    case rectangle_portrait_split_2x1_fill
    case rectangle_portrait_split_2x1_slash
    case rectangle_portrait_split_2x1_slash_fill
    case triangle_fill
    case triangle_tophalf_filled
    case triangle_bottomhalf_filled
    case triangle_inset_filled
    case diamond
    case diamond_fill
    case diamond_circle
    case diamond_circle_fill
    case diamond_inset_filled
    case octagon
    case octagon_fill
    case octagon_lefthalf_filled
    case octagon_righthalf_filled
    case octagon_tophalf_filled
    case octagon_bottomhalf_filled
    case hexagon_lefthalf_filled
    case hexagon_righthalf_filled
    case hexagon_tophalf_filled
    case hexagon_bottomhalf_filled
    case pentagon
    case pentagon_fill
    case pentagon_lefthalf_filled
    case pentagon_righthalf_filled
    case pentagon_tophalf_filled
    case pentagon_bottomhalf_filled
    case heart
    case heart_fill
    case heart_circle
    case heart_circle_fill
    case heart_square
    case heart_square_fill
    case heart_rectangle
    case heart_rectangle_fill
    case heart_slash
    case heart_slash_fill
    case heart_slash_circle
    case heart_slash_circle_fill
    case bolt_heart
    case bolt_heart_fill
    case arrow_up_heart
    case arrow_up_heart_fill
    case arrow_down_heart
    case arrow_down_heart_fill
    case arrow_clockwise_heart
    case arrow_clockwise_heart_fill
    case rhombus
    case rhombus_fill
    case star_leadinghalf_filled
    case star_circle
    case star_circle_fill
    case star_square
    case star_square_fill
    case star_slash
    case star_slash_fill
    case line_horizontal_star_fill_line_horizontal
    case flag
    case flag_fill
    case flag_circle
    case flag_circle_fill
    case flag_square
    case flag_square_fill
    case flag_slash
    case flag_slash_fill
    case flag_slash_circle
    case flag_slash_circle_fill
    case flag_badge_ellipsis
    case flag_badge_ellipsis_fill
    case flag_2_crossed
    case flag_2_crossed_fill
    case flag_filled_and_flag_crossed
    case flag_and_flag_filled_crossed
    case location
    case location_fill
    case location_circle
    case location_circle_fill
    case location_square
    case location_square_fill
    case location_slash
    case location_slash_fill
    case location_north
    case location_north_fill
    case location_north_circle
    case location_north_circle_fill
    case location_north_line
    case location_north_line_fill
    case sensor_tag_radiowaves_forward
    case sensor_tag_radiowaves_forward_fill
    case airtag_radiowaves_forward
    case airtag_radiowaves_forward_fill
    case airtag
    case airtag_fill
    case bell
    case bell_fill
    case bell_circle
    case bell_circle_fill
    case bell_square
    case bell_square_fill
    case bell_slash
    case bell_slash_fill
    case bell_slash_circle
    case bell_slash_circle_fill
    case bell_and_waveform
    case bell_and_waveform_fill
    case bell_badge
    case bell_badge_fill
    case bell_badge_circle
    case bell_badge_circle_fill
    case tag
    case tag_fill
    case tag_circle
    case tag_circle_fill
    case tag_square
    case tag_square_fill
    case tag_slash
    case tag_slash_fill
    case bolt
    case bolt_fill
    case bolt_circle
    case bolt_circle_fill
    case bolt_square
    case bolt_square_fill
    case bolt_ring_closed
    case bolt_shield
    case bolt_shield_fill
    case bolt_slash
    case bolt_slash_fill
    case bolt_slash_circle
    case bolt_slash_circle_fill
    case bolt_badge_a
    case bolt_badge_a_fill
    case bolt_horizontal
    case bolt_horizontal_fill
    case bolt_horizontal_circle
    case bolt_horizontal_circle_fill
    case eye
    case eye_fill
    case eye_circle
    case eye_circle_fill
    case eye_square
    case eye_square_fill
    case eye_slash
    case eye_slash_fill
    case eye_slash_circle
    case eye_slash_circle_fill
    case eye_trianglebadge_exclamationmark
    case eye_trianglebadge_exclamationmark_fill
    case tshirt
    case tshirt_fill
    case eyes
    case eyes_inverse
    case eyebrow
    case nose
    case nose_fill
    case mustache
    case mustache_fill
    case mouth
    case mouth_fill
    case eyeglasses
    case facemask
    case facemask_fill
    case brain_head_profile
    case brain
    case icloud
    case icloud_fill
    case icloud_circle
    case icloud_circle_fill
    case icloud_square
    case icloud_square_fill
    case icloud_slash
    case icloud_slash_fill
    case exclamationmark_icloud
    case exclamationmark_icloud_fill
    case checkmark_icloud
    case checkmark_icloud_fill
    case xmark_icloud
    case xmark_icloud_fill
    case link_icloud
    case link_icloud_fill
    case bolt_horizontal_icloud
    case bolt_horizontal_icloud_fill
    case person_icloud
    case person_icloud_fill
    case lock_icloud
    case lock_icloud_fill
    case key_icloud
    case key_icloud_fill
    case arrow_clockwise_icloud
    case arrow_clockwise_icloud_fill
    case arrow_counterclockwise_icloud
    case arrow_counterclockwise_icloud_fill
    case icloud_and_arrow_down
    case icloud_and_arrow_down_fill
    case icloud_and_arrow_up
    case icloud_and_arrow_up_fill
    case flashlight_off_fill
    case flashlight_on_fill
    case camera
    case camera_fill
    case camera_circle
    case camera_circle_fill
    case camera_shutter_button
    case camera_shutter_button_fill
    case camera_badge_ellipsis
    case camera_fill_badge_ellipsis
    case arrow_triangle_2_circlepath_camera
    case arrow_triangle_2_circlepath_camera_fill
    case camera_on_rectangle
    case camera_on_rectangle_fill
    case message
    case message_fill
    case message_circle
    case message_circle_fill
    case message_and_waveform
    case message_and_waveform_fill
    case arrow_up_message
    case arrow_up_message_fill
    case plus_message
    case plus_message_fill
    case bubble_right
    case bubble_right_fill
    case bubble_right_circle
    case bubble_right_circle_fill
    case bubble_left
    case bubble_left_fill
    case bubble_left_circle
    case bubble_left_circle_fill
    case exclamationmark_bubble
    case exclamationmark_bubble_fill
    case exclamationmark_bubble_circle
    case exclamationmark_bubble_circle_fill
    case quote_opening
    case quote_closing
    case quote_bubble
    case quote_bubble_fill
    case star_bubble
    case star_bubble_fill
    case character_bubble
    case character_bubble_fill
    case text_bubble
    case text_bubble_fill
    case captions_bubble
    case captions_bubble_fill
    case plus_bubble
    case plus_bubble_fill
    case checkmark_bubble
    case checkmark_bubble_fill
    case rectangle_3_group_bubble_left
    case rectangle_3_group_bubble_left_fill
    case ellipsis_bubble
    case ellipsis_bubble_fill
    case ellipsis_vertical_bubble
    case ellipsis_vertical_bubble_fill
    case phone_bubble_left
    case phone_bubble_left_fill
    case video_bubble_left
    case video_bubble_left_fill
    case bubble_middle_bottom
    case bubble_middle_bottom_fill
    case bubble_middle_top
    case bubble_middle_top_fill
    case bubble_left_and_bubble_right
    case bubble_left_and_bubble_right_fill
    case bubble_left_and_exclamationmark_bubble_right
    case bubble_left_and_exclamationmark_bubble_right_fill
    case phone
    case phone_fill
    case phone_circle
    case phone_circle_fill
    case phone_badge_plus
    case phone_fill_badge_plus
    case phone_connection
    case phone_fill_connection
    case phone_and_waveform
    case phone_and_waveform_fill
    case phone_arrow_up_right
    case phone_fill_arrow_up_right
    case phone_arrow_down_left
    case phone_fill_arrow_down_left
    case phone_arrow_right
    case phone_fill_arrow_right
    case phone_down
    case phone_down_fill
    case phone_down_circle
    case phone_down_circle_fill
    case teletype
    case teletype_circle
    case teletype_circle_fill
    case teletype_answer
    case teletype_answer_circle
    case teletype_answer_circle_fill
    case video
    case video_fill
    case video_circle
    case video_circle_fill
    case video_square
    case video_square_fill
    case video_slash
    case video_slash_fill
    case video_badge_plus
    case video_fill_badge_plus
    case video_badge_checkmark
    case video_fill_badge_checkmark
    case video_badge_ellipsis
    case video_fill_badge_ellipsis
    case video_and_waveform
    case video_and_waveform_fill
    case arrow_up_right_video
    case arrow_up_right_video_fill
    case arrow_down_left_video
    case arrow_down_left_video_fill
    case questionmark_video
    case questionmark_video_fill
    case envelope
    case envelope_fill
    case envelope_circle
    case envelope_circle_fill
    case envelope_arrow_triangle_branch
    case envelope_arrow_triangle_branch_fill
    case envelope_open
    case envelope_open_fill
    case envelope_badge
    case envelope_badge_fill
    case envelope_badge_shield_half_filled
    case envelope_badge_shield_half_filled_fill
    case mail_stack
    case mail_stack_fill
    case mail
    case mail_fill
    case mail_and_text_magnifyingglass
    case rectangle_and_text_magnifyingglass
    case arrow_up_right_and_arrow_down_left_rectangle
    case arrow_up_right_and_arrow_down_left_rectangle_fill
    case gear
    case gear_circle
    case gear_circle_fill
    case gear_badge_checkmark
    case gear_badge_xmark
    case gear_badge_questionmark
    case gearshape
    case gearshape_fill
    case gearshape_circle
    case gearshape_circle_fill
    case gearshape_2
    case gearshape_2_fill
    case signature
    case line_3_crossed_swirl_circle
    case line_3_crossed_swirl_circle_fill
    case scissors
    case scissors_circle
    case scissors_circle_fill
    case scissors_badge_ellipsis
    case ellipsis
    case ellipsis_circle
    case ellipsis_circle_fill
    case ellipsis_rectangle
    case ellipsis_rectangle_fill
    case bag
    case bag_fill
    case bag_circle
    case bag_circle_fill
    case bag_badge_plus
    case bag_fill_badge_plus
    case bag_badge_minus
    case bag_fill_badge_minus
    case cart
    case cart_fill
    case cart_circle
    case cart_circle_fill
    case cart_badge_plus
    case cart_fill_badge_plus
    case cart_badge_minus
    case cart_fill_badge_minus
    case creditcard
    case creditcard_fill
    case creditcard_circle
    case creditcard_circle_fill
    case creditcard_and_123
    case creditcard_trianglebadge_exclamationmark
    case giftcard
    case giftcard_fill
    case wallet_pass
    case wallet_pass_fill
    case wand_and_rays
    case wand_and_rays_inverse
    case wand_and_stars
    case wand_and_stars_inverse
    case crop
    case crop_rotate
    case dial_min
    case dial_min_fill
    case dial_max
    case dial_max_fill
    case gyroscope
    case nosign
    case gauge
    case gauge_badge_plus
    case gauge_badge_minus
    case speedometer
    case barometer
    case metronome
    case metronome_fill
    case amplifier
    case dice
    case dice_fill
    case die_face_1_fill
    case die_face_2_fill
    case die_face_3_fill
    case die_face_4_fill
    case die_face_5_fill
    case die_face_6_fill
    case square_grid_3x3_square
    case pianokeys
    case pianokeys_inverse
    case tuningfork
    case paintbrush
    case paintbrush_fill
    case paintbrush_pointed
    case paintbrush_pointed_fill
    case bandage
    case bandage_fill
    case ruler
    case ruler_fill
    case level
    case level_fill
    case lines_measurement_horizontal
    case wrench
    case wrench_fill
    case hammer
    case hammer_fill
    case hammer_circle
    case hammer_circle_fill
    case screwdriver
    case screwdriver_fill
    case eyedropper
    case eyedropper_halffull
    case eyedropper_full
    case wrench_and_screwdriver
    case wrench_and_screwdriver_fill
    case applescript
    case applescript_fill
    case scroll
    case scroll_fill
    case stethoscope
    case stethoscope_circle
    case stethoscope_circle_fill
    case printer
    case printer_fill
    case printer_filled_and_paper
    case printer_dotmatrix
    case printer_dotmatrix_fill
    case printer_dotmatrix_filled_and_paper
    case scanner
    case scanner_fill
    case faxmachine
    case briefcase
    case briefcase_fill
    case briefcase_circle
    case briefcase_circle_fill
    case `case`
    case case_fill
    case latch_2_case
    case latch_2_case_fill
    case cross_case
    case cross_case_fill
    case suitcase
    case suitcase_fill
    case suitcase_cart
    case suitcase_cart_fill
    case theatermasks
    case theatermasks_fill
    case theatermasks_circle
    case theatermasks_circle_fill
    case puzzlepiece_extension
    case puzzlepiece_extension_fill
    case puzzlepiece
    case puzzlepiece_fill
    case homekit
    case house
    case house_fill
    case house_circle
    case house_circle_fill
    case music_note_house
    case music_note_house_fill
    case building_columns
    case building_columns_fill
    case building_columns_circle
    case building_columns_circle_fill
    case signpost_left
    case signpost_left_fill
    case signpost_right
    case signpost_right_fill
    case square_split_bottomrightquarter
    case square_split_bottomrightquarter_fill
    case building
    case building_fill
    case building_2
    case building_2_fill
    case building_2_crop_circle
    case building_2_crop_circle_fill
    case lock
    case lock_fill
    case lock_circle
    case lock_circle_fill
    case lock_square
    case lock_square_fill
    case lock_square_stack
    case lock_square_stack_fill
    case lock_rectangle
    case lock_rectangle_fill
    case lock_rectangle_stack
    case lock_rectangle_stack_fill
    case lock_rectangle_on_rectangle
    case lock_rectangle_on_rectangle_fill
    case lock_shield
    case lock_shield_fill
    case lock_slash
    case lock_slash_fill
    case lock_open
    case lock_open_fill
    case lock_rotation
    case lock_rotation_open
    case key
    case key_fill
    case wifi
    case wifi_circle
    case wifi_circle_fill
    case wifi_square
    case wifi_square_fill
    case wifi_slash
    case wifi_exclamationmark
    case pin
    case pin_fill
    case pin_circle
    case pin_circle_fill
    case pin_square
    case pin_square_fill
    case pin_slash
    case pin_slash_fill
    case mappin
    case mappin_circle
    case mappin_circle_fill
    case mappin_square
    case mappin_square_fill
    case mappin_slash
    case mappin_slash_circle
    case mappin_slash_circle_fill
    case mappin_and_ellipse
    case map
    case map_fill
    case map_circle
    case map_circle_fill
    case safari
    case safari_fill
    case move_3d
    case scale_3d
    case rotate_3d
    case torus
    case rotate_left
    case rotate_left_fill
    case rotate_right
    case rotate_right_fill
    case selection_pin_in_out
    case powerplug
    case powerplug_fill
    case timeline_selection
    case cpu
    case cpu_fill
    case memorychip
    case memorychip_fill
    case opticaldisc
    case display
    case lock_display
    case lock_open_display
    case display_and_arrow_down
    case display_trianglebadge_exclamationmark
    case display_2
    case desktopcomputer
    case lock_desktopcomputer
    case lock_open_desktopcomputer
    case desktopcomputer_and_arrow_down
    case desktopcomputer_trianglebadge_exclamationmark
    case pc
    case macpro_gen1
    case macpro_gen1_fill
    case macpro_gen2
    case macpro_gen2_fill
    case macpro_gen3
    case macpro_gen3_fill
    case macpro_gen3_server
    case server_rack
    case xserve
    case laptopcomputer
    case lock_laptopcomputer
    case lock_open_laptopcomputer
    case laptopcomputer_and_arrow_down
    case laptopcomputer_trianglebadge_exclamationmark
    case laptopcomputer_and_iphone
    case ipad_and_iphone
    case macmini
    case macmini_fill
    case airport_express
    case airport_extreme
    case airport_extreme_tower
    case ipod
    case ipodshuffle_gen1
    case ipodshuffle_gen2
    case ipodshuffle_gen3
    case ipodshuffle_gen4
    case ipodtouch
    case ipodtouch_slash
    case ipodtouch_landscape
    case flipphone
    case candybarphone
    case iphone_homebutton
    case iphone_homebutton_circle
    case iphone_homebutton_circle_fill
    case iphone_homebutton_landscape
    case iphone_homebutton_radiowaves_left_and_right
    case iphone_homebutton_radiowaves_left_and_right_circle
    case iphone_homebutton_radiowaves_left_and_right_circle_fill
    case iphone_homebutton_slash
    case iphone_homebutton_slash_circle
    case iphone_homebutton_slash_circle_fill
    case iphone_homebutton_badge_play
    case iphone
    case iphone_circle
    case iphone_circle_fill
    case iphone_landscape
    case iphone_radiowaves_left_and_right
    case iphone_radiowaves_left_and_right_circle
    case iphone_radiowaves_left_and_right_circle_fill
    case iphone_slash
    case iphone_slash_circle
    case iphone_slash_circle_fill
    case iphone_badge_play
    case lock_iphone
    case lock_open_iphone
    case iphone_and_arrow_forward
    case arrow_turn_up_forward_iphone
    case arrow_turn_up_forward_iphone_fill
    case iphone_rear_camera
    case apps_iphone
    case apps_iphone_badge_plus
    case apps_iphone_landscape
    case platter_filled_top_iphone
    case platter_filled_bottom_iphone
    case platter_filled_top_and_arrow_up_iphone
    case platter_filled_bottom_and_arrow_down_iphone
    case platter_2_filled_iphone
    case platter_2_filled_iphone_landscape
    case iphone_smartbatterycase_gen2
    case iphone_smartbatterycase_gen1
    case ipad_homebutton
    case ipad_homebutton_badge_play
    case ipad_homebutton_landscape
    case ipad_homebutton_landscape_badge_play
    case ipad
    case ipad_badge_play
    case lock_ipad
    case lock_open_ipad
    case ipad_and_arrow_forward
    case ipad_landscape
    case ipad_landscape_badge_play
    case ipad_rear_camera
    case apps_ipad
    case apps_ipad_landscape
    case platter_2_filled_ipad
    case platter_2_filled_ipad_landscape
    case applepencil
    case magicmouse
    case magicmouse_fill
    case computermouse
    case computermouse_fill
    case applewatch
    case applewatch_watchface
    case exclamationmark_applewatch
    case lock_applewatch
    case lock_open_applewatch
    case applewatch_radiowaves_left_and_right
    case applewatch_slash
    case applewatch_side_right
    case watchface_applewatch_case
    case applewatch_case_inset_filled
    case platter_filled_top_applewatch_case
    case platter_filled_bottom_applewatch_case
    case platter_top_applewatch_case
    case platter_bottom_applewatch_case
    case digitalcrown_arrow_clockwise
    case digitalcrown_arrow_clockwise_fill
    case digitalcrown_arrow_counterclockwise
    case digitalcrown_arrow_counterclockwise_fill
    case digitalcrown_press
    case digitalcrown_press_fill
    case digitalcrown_horizontal_arrow_clockwise
    case digitalcrown_horizontal_arrow_clockwise_fill
    case digitalcrown_horizontal_arrow_counterclockwise
    case digitalcrown_horizontal_arrow_counterclockwise_fill
    case digitalcrown_horizontal_press
    case digitalcrown_horizontal_press_fill
    case airpodsmax
    case beats_headphones
    case headphones
    case headphones_circle
    case headphones_circle_fill
    case earbuds
    case earbuds_case
    case earbuds_case_fill
    case earpods
    case airpods
    case airpod_right
    case airpod_left
    case airpods_chargingcase
    case airpods_chargingcase_fill
    case airpods_chargingcase_wireless
    case airpods_chargingcase_wireless_fill
    case airpodspro
    case airpodpro_right
    case airpodpro_left
    case airpodspro_chargingcase_wireless
    case airpodspro_chargingcase_wireless_fill
    case airpods_gen3
    case airpod_gen3_right
    case airpod_gen3_left
    case airpods_gen3_chargingcase_wireless
    case airpods_gen3_chargingcase_wireless_fill
    case beats_earphones
    case beats_powerbeatspro
    case beats_powerbeatspro_right
    case beats_powerbeatspro_left
    case beats_powerbeats
    case beats_powerbeats3
    case beats_studiobuds
    case beats_studiobud_left
    case beats_studiobud_right
    case beats_studiobuds_chargingcase
    case beats_studiobuds_chargingcase_fill
    case beats_fit_pro
    case beats_fit_pro_left
    case beats_fit_pro_right
    case beats_fit_pro_chargingcase
    case beats_fit_pro_chargingcase_fill
    case beats_powerbeatspro_chargingcase
    case beats_powerbeatspro_chargingcase_fill
    case homepodmini
    case homepodmini_fill
    case homepodmini_2
    case homepodmini_2_fill
    case homepod_and_homepodmini
    case homepod_and_homepodmini_fill
    case hifispeaker_and_homepodmini
    case hifispeaker_and_homepodmini_fill
    case homepod
    case homepod_fill
    case homepod_2
    case homepod_2_fill
    case hifispeaker_and_homepod
    case hifispeaker_and_homepod_fill
    case hifispeaker
    case hifispeaker_fill
    case hifispeaker_2
    case hifispeaker_2_fill
    case appletv
    case appletv_fill
    case homepod_and_appletv
    case homepod_and_appletv_fill
    case homepodmini_and_appletv
    case homepodmini_and_appletv_fill
    case hifispeaker_and_appletv
    case hifispeaker_and_appletv_fill
    case appletvremote_gen1
    case appletvremote_gen1_fill
    case appletvremote_gen2
    case appletvremote_gen2_fill
    case appletvremote_gen3
    case appletvremote_gen3_fill
    case appletvremote_gen4
    case appletvremote_gen4_fill
    case magsafe_batterypack
    case magsafe_batterypack_fill
    case mediastick
    case cable_connector
    case cable_connector_horizontal
    case radio
    case radio_fill
    case tv
    case tv_fill
    case tv_inset_filled
    case tv_circle
    case tv_circle_fill
    case sparkles_tv
    case sparkles_tv_fill
    case _4k_tv
    case _4k_tv_fill
    case music_note_tv
    case music_note_tv_fill
    case play_tv
    case play_tv_fill
    case photo_tv
    case tv_and_hifispeaker_fill
    case tv_and_mediabox
    case airplayvideo
    case airplayvideo_circle
    case airplayvideo_circle_fill
    case airplayvideo_badge_exclamationmark
    case airplayaudio
    case airplayaudio_circle
    case airplayaudio_circle_fill
    case airplayaudio_badge_exclamationmark
    case dot_radiowaves_left_and_right
    case dot_radiowaves_right
    case dot_radiowaves_forward
    case wave_3_left
    case wave_3_left_circle
    case wave_3_left_circle_fill
    case wave_3_backward
    case wave_3_backward_circle
    case wave_3_backward_circle_fill
    case wave_3_right
    case wave_3_right_circle
    case wave_3_right_circle_fill
    case wave_3_forward
    case wave_3_forward_circle
    case wave_3_forward_circle_fill
    case dot_radiowaves_up_forward
    case antenna_radiowaves_left_and_right
    case antenna_radiowaves_left_and_right_slash
    case antenna_radiowaves_left_and_right_circle
    case antenna_radiowaves_left_and_right_circle_fill
    case pip
    case pip_fill
    case pip_exit
    case pip_enter
    case pip_swap
    case pip_remove
    case rectangle_arrowtriangle_2_outward
    case rectangle_arrowtriangle_2_inward
    case rectangle_portrait_arrowtriangle_2_outward
    case rectangle_portrait_arrowtriangle_2_inward
    case rectangle_2_swap
    case guitars
    case guitars_fill
    case airplane_circle
    case airplane_circle_fill
    case airplane_arrival
    case airplane_departure
    case car
    case car_fill
    case car_circle
    case car_circle_fill
    case bolt_car
    case bolt_car_fill
    case bolt_car_circle
    case bolt_car_circle_fill
    case car_2
    case car_2_fill
    case bus
    case bus_fill
    case bus_doubledecker
    case bus_doubledecker_fill
    case tram
    case tram_fill
    case tram_circle
    case tram_circle_fill
    case tram_fill_tunnel
    case cablecar
    case cablecar_fill
    case ferry
    case ferry_fill
    case car_ferry
    case car_ferry_fill
    case train_side_front_car
    case train_side_middle_car
    case train_side_rear_car
    case bicycle
    case bicycle_circle
    case bicycle_circle_fill
    case scooter
    case parkingsign
    case parkingsign_circle
    case parkingsign_circle_fill
    case fuelpump
    case fuelpump_fill
    case fuelpump_circle
    case fuelpump_circle_fill
    case fanblades
    case fanblades_fill
    case bed_double
    case bed_double_fill
    case bed_double_circle
    case bed_double_circle_fill
    case lungs
    case lungs_fill
    case allergens
    case pills
    case pills_fill
    case pills_circle
    case pills_circle_fill
    case testtube_2
    case ivfluid_bag
    case ivfluid_bag_fill
    case cross_vial
    case cross_vial_fill
    case cross
    case cross_fill
    case cross_circle
    case cross_circle_fill
    case hare
    case hare_fill
    case tortoise
    case tortoise_fill
    case pawprint
    case pawprint_fill
    case pawprint_circle
    case pawprint_circle_fill
    case ant
    case ant_fill
    case ant_circle
    case ant_circle_fill
    case ladybug
    case ladybug_fill
    case leaf
    case leaf_fill
    case leaf_circle
    case leaf_circle_fill
    case leaf_arrow_triangle_circlepath
    case film
    case film_fill
    case film_circle
    case film_circle_fill
    case sportscourt
    case sportscourt_fill
    case face_smiling
    case face_smiling_fill
    case face_dashed
    case face_dashed_fill
    case crown
    case crown_fill
    case comb
    case comb_fill
    case qrcode
    case barcode
    case viewfinder
    case viewfinder_circle
    case viewfinder_circle_fill
    case barcode_viewfinder
    case qrcode_viewfinder
    case plus_viewfinder
    case camera_viewfinder
    case faceid
    case doc_viewfinder
    case doc_viewfinder_fill
    case location_viewfinder
    case location_fill_viewfinder
    case person_fill_viewfinder
    case text_viewfinder
    case dot_viewfinder
    case dot_circle_viewfinder
    case photo
    case photo_fill
    case photo_circle
    case photo_circle_fill
    case text_below_photo
    case text_below_photo_fill
    case checkerboard_rectangle
    case camera_metering_center_weighted_average
    case camera_metering_center_weighted
    case camera_metering_matrix
    case camera_metering_multispot
    case camera_metering_none
    case camera_metering_partial
    case camera_metering_spot
    case camera_metering_unknown
    case camera_aperture
    case rectangle_dashed
    case rectangle_dashed_badge_record
    case rectangle_badge_plus
    case rectangle_fill_badge_plus
    case rectangle_badge_minus
    case rectangle_fill_badge_minus
    case rectangle_badge_checkmark
    case rectangle_fill_badge_checkmark
    case rectangle_badge_xmark
    case rectangle_fill_badge_xmark
    case rectangle_badge_person_crop
    case rectangle_fill_badge_person_crop
    case photo_on_rectangle
    case photo_fill_on_rectangle_fill
    case rectangle_on_rectangle_angled
    case rectangle_fill_on_rectangle_angled_fill
    case photo_on_rectangle_angled
    case rectangle_stack
    case rectangle_stack_fill
    case rectangle_stack_badge_plus
    case rectangle_stack_fill_badge_plus
    case rectangle_stack_badge_minus
    case rectangle_stack_fill_badge_minus
    case rectangle_stack_badge_person_crop
    case rectangle_stack_badge_person_crop_fill
    case rectangle_stack_badge_play
    case rectangle_stack_badge_play_fill
    case sparkles_rectangle_stack
    case sparkles_rectangle_stack_fill
    case sidebar_left
    case sidebar_right
    case sidebar_leading
    case sidebar_trailing
    case sidebar_squares_left
    case sidebar_squares_right
    case sidebar_squares_leading
    case sidebar_squares_trailing
    case macwindow
    case macwindow_badge_plus
    case slider_horizontal_2_rectangle_and_arrow_triangle_2_circlepath
    case dock_rectangle
    case dock_arrow_up_rectangle
    case dock_arrow_down_rectangle
    case menubar_rectangle
    case menubar_dock_rectangle
    case menubar_dock_rectangle_badge_record
    case menubar_arrow_up_rectangle
    case menubar_arrow_down_rectangle
    case macwindow_on_rectangle
    case text_and_command_macwindow
    case keyboard_macwindow
    case uiwindow_split_2x1
    case mosaic
    case mosaic_fill
    case squares_below_rectangle
    case rectangle_split_3x3_fill
    case square_on_square_squareshape_controlhandles
    case squareshape_controlhandles_on_squareshape_controlhandles
    case pano
    case pano_fill
    case circle_grid_2x1
    case circle_grid_2x1_fill
    case circle_grid_2x1_left_filled
    case circle_grid_2x1_right_filled
    case square_and_line_vertical_and_square
    case square_fill_and_line_vertical_and_square_fill
    case square_filled_and_line_vertical_and_square
    case square_and_line_vertical_and_square_filled
    case flowchart
    case flowchart_fill
    case rectangle_connected_to_line_below
    case align_horizontal_left
    case align_horizontal_left_fill
    case align_horizontal_center
    case align_horizontal_center_fill
    case align_horizontal_right
    case align_horizontal_right_fill
    case align_vertical_top
    case align_vertical_top_fill
    case align_vertical_center
    case align_vertical_center_fill
    case align_vertical_bottom
    case align_vertical_bottom_fill
    case shield
    case shield_fill
    case shield_lefthalf_filled
    case shield_righthalf_filled
    case shield_slash
    case shield_slash_fill
    case shield_lefthalf_filled_slash
    case checkerboard_shield
    case switch_2
    case point_topleft_down_curvedto_point_bottomright_up
    case point_topleft_down_curvedto_point_bottomright_up_fill
    case point_topleft_down_curvedto_point_filled_bottomright_up
    case point_filled_topleft_down_curvedto_point_bottomright_up
    case app_connected_to_app_below_fill
    case slider_horizontal_3
    case slider_horizontal_below_rectangle
    case slider_horizontal_below_square_filled_and_square
    case slider_vertical_3
    case cube
    case cube_fill
    case cube_transparent
    case cube_transparent_fill
    case shippingbox
    case shippingbox_fill
    case shippingbox_circle
    case shippingbox_circle_fill
    case arkit
    case arkit_badge_xmark
    case cone
    case cone_fill
    case pyramid
    case pyramid_fill
    case square_stack_3d_down_right
    case square_stack_3d_down_right_fill
    case square_stack_3d_down_forward
    case square_stack_3d_down_forward_fill
    case square_stack_3d_up
    case square_stack_3d_up_fill
    case square_stack_3d_up_slash
    case square_stack_3d_up_slash_fill
    case square_stack_3d_up_badge_a
    case square_stack_3d_up_badge_a_fill
    case square_stack_3d_forward_dottedline
    case square_stack_3d_forward_dottedline_fill
    case livephoto
    case livephoto_slash
    case livephoto_badge_a
    case livephoto_play
    case scope
    case helm
    case clock
    case clock_fill
    case clock_circle
    case clock_circle_fill
    case clock_badge_checkmark
    case clock_badge_checkmark_fill
    case clock_badge_exclamationmark
    case clock_badge_exclamationmark_fill
    case deskclock
    case deskclock_fill
    case alarm
    case alarm_fill
    case stopwatch
    case stopwatch_fill
    case chart_xyaxis_line
    case timer
    case timer_square
    case clock_arrow_circlepath
    case exclamationmark_arrow_circlepath
    case clock_arrow_2_circlepath
    case gamecontroller
    case gamecontroller_fill
    case l_joystick
    case l_joystick_fill
    case r_joystick
    case r_joystick_fill
    case l_joystick_press_down
    case l_joystick_press_down_fill
    case r_joystick_press_down
    case r_joystick_press_down_fill
    case l_joystick_tilt_left
    case l_joystick_tilt_left_fill
    case l_joystick_tilt_right
    case l_joystick_tilt_right_fill
    case l_joystick_tilt_up
    case l_joystick_tilt_up_fill
    case l_joystick_tilt_down
    case l_joystick_tilt_down_fill
    case r_joystick_tilt_left
    case r_joystick_tilt_left_fill
    case r_joystick_tilt_right
    case r_joystick_tilt_right_fill
    case r_joystick_tilt_up
    case r_joystick_tilt_up_fill
    case r_joystick_tilt_down
    case r_joystick_tilt_down_fill
    case dpad
    case dpad_fill
    case dpad_left_filled
    case dpad_up_filled
    case dpad_right_filled
    case dpad_down_filled
    case circle_circle
    case circle_circle_fill
    case square_circle
    case square_circle_fill
    case triangle_circle
    case triangle_circle_fill
    case rectangle_roundedtop
    case rectangle_roundedtop_fill
    case rectangle_roundedbottom
    case rectangle_roundedbottom_fill
    case l_rectangle_roundedbottom
    case l_rectangle_roundedbottom_fill
    case l1_rectangle_roundedbottom
    case l1_rectangle_roundedbottom_fill
    case l2_rectangle_roundedtop
    case l2_rectangle_roundedtop_fill
    case r_rectangle_roundedbottom
    case r_rectangle_roundedbottom_fill
    case r1_rectangle_roundedbottom
    case r1_rectangle_roundedbottom_fill
    case r2_rectangle_roundedtop
    case r2_rectangle_roundedtop_fill
    case lb_rectangle_roundedbottom
    case lb_rectangle_roundedbottom_fill
    case rb_rectangle_roundedbottom
    case rb_rectangle_roundedbottom_fill
    case lt_rectangle_roundedtop
    case lt_rectangle_roundedtop_fill
    case rt_rectangle_roundedtop
    case rt_rectangle_roundedtop_fill
    case zl_rectangle_roundedtop
    case zl_rectangle_roundedtop_fill
    case zr_rectangle_roundedtop
    case zr_rectangle_roundedtop_fill
    case logo_playstation
    case logo_xbox
    case paintpalette
    case paintpalette_fill
    case cup_and_saucer
    case cup_and_saucer_fill
    case takeoutbag_and_cup_and_straw
    case takeoutbag_and_cup_and_straw_fill
    case fork_knife
    case fork_knife_circle
    case fork_knife_circle_fill
    case figure_walk
    case figure_walk_circle
    case figure_walk_circle_fill
    case figure_walk_diamond
    case figure_walk_diamond_fill
    case figure_stand
    case figure_stand_line_dotted_figure_stand
    case figure_wave
    case figure_wave_circle
    case figure_wave_circle_fill
    case figure_roll
    case ear
    case ear_badge_checkmark
    case ear_trianglebadge_exclamationmark
    case ear_and_waveform
    case ear_fill
    case hearingdevice_ear
    case hand_raised
    case hand_raised_fill
    case hand_raised_circle
    case hand_raised_circle_fill
    case hand_raised_square
    case hand_raised_square_fill
    case hand_raised_slash
    case hand_raised_slash_fill
    case hand_thumbsup
    case hand_thumbsup_fill
    case hand_thumbsup_circle
    case hand_thumbsup_circle_fill
    case hand_thumbsdown
    case hand_thumbsdown_fill
    case hand_thumbsdown_circle
    case hand_thumbsdown_circle_fill
    case hand_point_up_left
    case hand_point_up_left_fill
    case hand_draw
    case hand_draw_fill
    case hand_tap
    case hand_tap_fill
    case rectangle_and_hand_point_up_left
    case rectangle_and_hand_point_up_left_fill
    case rectangle_filled_and_hand_point_up_left
    case rectangle_and_hand_point_up_left_filled
    case hand_point_left
    case hand_point_left_fill
    case hand_point_right
    case hand_point_right_fill
    case hand_point_up
    case hand_point_up_fill
    case hand_point_up_braille
    case hand_point_up_braille_fill
    case hand_point_down
    case hand_point_down_fill
    case hand_wave
    case hand_wave_fill
    case hands_clap
    case hands_clap_fill
    case hands_sparkles
    case hands_sparkles_fill
    case rectangle_compress_vertical
    case rectangle_expand_vertical
    case rectangle_and_arrow_up_right_and_arrow_down_left
    case rectangle_and_arrow_up_right_and_arrow_down_left_slash
    case square_2_stack_3d
    case square_2_stack_3d_top_filled
    case square_2_stack_3d_bottom_filled
    case square_3_layers_3d_down_right
    case square_3_layers_3d_down_right_slash
    case square_3_layers_3d_down_left
    case square_3_layers_3d_down_left_slash
    case square_3_layers_3d_down_forward
    case square_3_layers_3d_down_backward
    case square_3_stack_3d
    case square_3_stack_3d_slash
    case square_3_stack_3d_top_filled
    case square_3_stack_3d_middle_filled
    case square_3_stack_3d_bottom_filled
    case cylinder
    case cylinder_fill
    case cylinder_split_1x2
    case cylinder_split_1x2_fill
    case chart_bar
    case chart_bar_fill
    case chart_pie
    case chart_pie_fill
    case chart_bar_xaxis
    case chart_line_uptrend_xyaxis
    case chart_line_uptrend_xyaxis_circle
    case chart_line_uptrend_xyaxis_circle_fill
    case dot_squareshape_split_2x2
    case squareshape_split_2x2_dotted
    case squareshape_split_2x2
    case squareshape_split_3x3
    case burst
    case burst_fill
    case waveform_path_ecg
    case waveform_path_ecg_rectangle
    case waveform_path_ecg_rectangle_fill
    case waveform_path
    case waveform_path_badge_plus
    case waveform_path_badge_minus
    case point_3_connected_trianglepath_dotted
    case point_3_filled_connected_trianglepath_dotted
    case waveform
    case waveform_circle
    case waveform_circle_fill
    case waveform_badge_plus
    case waveform_badge_minus
    case waveform_badge_exclamationmark
    case waveform_and_magnifyingglass
    case waveform_and_mic
    case staroflife
    case staroflife_fill
    case staroflife_circle
    case staroflife_circle_fill
    case simcard
    case simcard_fill
    case simcard_2
    case simcard_2_fill
    case sdcard
    case sdcard_fill
    case esim
    case esim_fill
    case touchid
    case bonjour
    case atom
    case scalemass
    case scalemass_fill
    case gift
    case gift_fill
    case gift_circle
    case gift_circle_fill
    case plus_app
    case plus_app_fill
    case arrow_down_app
    case arrow_down_app_fill
    case arrow_up_forward_app
    case arrow_up_forward_app_fill
    case xmark_app
    case xmark_app_fill
    case questionmark_app
    case questionmark_app_fill
    case app_badge
    case app_badge_fill
    case app_badge_checkmark
    case app_badge_checkmark_fill
    case app_dashed
    case questionmark_app_dashed
    case appclip
    case app_gift
    case app_gift_fill
    case studentdesk
    case hourglass
    case hourglass_circle
    case hourglass_circle_fill
    case hourglass_badge_plus
    case hourglass_bottomhalf_filled
    case hourglass_tophalf_filled
    case banknote
    case banknote_fill
    case purchased
    case purchased_circle
    case purchased_circle_fill
    case perspective
    case circle_and_line_horizontal
    case circle_and_line_horizontal_fill
    case trapezoid_and_line_vertical
    case trapezoid_and_line_vertical_fill
    case trapezoid_and_line_horizontal
    case trapezoid_and_line_horizontal_fill
    case aspectratio
    case aspectratio_fill
    case camera_filters
    case skew
    case arrow_left_and_right_righttriangle_left_righttriangle_right
    case arrow_left_and_right_righttriangle_left_righttriangle_right_fill
    case arrow_up_and_down_righttriangle_up_righttriangle_down
    case arrow_up_and_down_righttriangle_up_righttriangle_down_fill
    case arrowtriangle_left_and_line_vertical_and_arrowtriangle_right
    case arrowtriangle_left_and_line_vertical_and_arrowtriangle_right_fill
    case arrowtriangle_right_and_line_vertical_and_arrowtriangle_left
    case arrowtriangle_right_and_line_vertical_and_arrowtriangle_left_fill
    case grid
    case grid_circle
    case grid_circle_fill
    case burn
    case lifepreserver
    case lifepreserver_fill
    case recordingtape
    case binoculars
    case binoculars_fill
    case battery_100
    case battery_75
    case battery_50
    case battery_25
    case battery_0
    case battery_100_bolt
    case minus_plus_batteryblock
    case minus_plus_batteryblock_fill
    case bolt_batteryblock
    case bolt_batteryblock_fill
    case lightbulb
    case lightbulb_fill
    case lightbulb_circle
    case lightbulb_circle_fill
    case lightbulb_slash
    case lightbulb_slash_fill
    case fibrechannel
    case checklist
    case square_fill_text_grid_1x2
    case list_dash
    case list_bullet
    case list_bullet_circle
    case list_bullet_circle_fill
    case list_triangle
    case list_bullet_indent
    case list_number
    case list_star
    case increase_indent
    case decrease_indent
    case decrease_quotelevel
    case increase_quotelevel
    case list_bullet_below_rectangle
    case text_badge_plus
    case text_badge_minus
    case text_badge_checkmark
    case text_badge_xmark
    case text_badge_star
    case text_insert
    case text_append
    case text_quote
    case text_alignleft
    case text_aligncenter
    case text_alignright
    case text_justify
    case text_justify_left
    case text_justify_right
    case text_justify_leading
    case text_justify_trailing
    case text_redaction
    case list_and_film
    case line_3_horizontal
    case line_3_horizontal_decrease
    case line_3_horizontal_decrease_circle
    case line_3_horizontal_decrease_circle_fill
    case line_3_horizontal_circle
    case line_3_horizontal_circle_fill
    case line_2_horizontal_decrease_circle
    case line_2_horizontal_decrease_circle_fill
    case character
    case textformat_size_smaller
    case textformat_size_larger
    case textformat_size
    case textformat
    case textformat_alt
    case textformat_superscript
    case textformat_subscript
    case abc
    case textformat_abc
    case textformat_abc_dottedunderline
    case bold
    case italic
    case underline
    case strikethrough
    case shadow
    case bold_italic_underline
    case bold_underline
    case view_2d
    case view_3d
    case character_cursor_ibeam
    case fx
    case f_cursive
    case f_cursive_circle
    case f_cursive_circle_fill
    case k
    case sum
    case percent
    case function
    case fn
    case textformat_123
    case _123_rectangle
    case _123_rectangle_fill
    case character_textbox
    case a_magnify
    case info
    case info_circle
    case info_circle_fill
    case at
    case at_circle
    case at_circle_fill
    case at_badge_plus
    case at_badge_minus
    case questionmark
    case questionmark_circle
    case questionmark_circle_fill
    case questionmark_square
    case questionmark_square_fill
    case questionmark_diamond
    case exclamationmark
    case exclamationmark_2
    case exclamationmark_3
    case exclamationmark_circle
    case exclamationmark_circle_fill
    case exclamationmark_square
    case exclamationmark_square_fill
    case exclamationmark_octagon
    case exclamationmark_octagon_fill
    case exclamationmark_shield
    case exclamationmark_shield_fill
    case plus
    case plus_circle_fill
    case plus_square
    case plus_square_fill
    case plus_rectangle
    case plus_rectangle_fill
    case plus_rectangle_portrait
    case plus_rectangle_portrait_fill
    case plus_diamond
    case plus_diamond_fill
    case minus
    case minus_circle_fill
    case minus_square
    case minus_square_fill
    case minus_rectangle
    case minus_rectangle_fill
    case minus_rectangle_portrait
    case minus_rectangle_portrait_fill
    case minus_diamond
    case minus_diamond_fill
    case plusminus
    case plusminus_circle
    case plusminus_circle_fill
    case plus_forwardslash_minus
    case minus_forwardslash_plus
    case multiply
    case multiply_circle_fill
    case multiply_square_fill
    case xmark_rectangle
    case xmark_rectangle_fill
    case xmark_rectangle_portrait
    case xmark_rectangle_portrait_fill
    case xmark_diamond
    case xmark_diamond_fill
    case xmark_shield
    case xmark_shield_fill
    case xmark_octagon
    case xmark_octagon_fill
    case divide
    case divide_circle
    case divide_circle_fill
    case divide_square
    case divide_square_fill
    case equal
    case equal_circle_fill
    case equal_square
    case equal_square_fill
    case lessthan
    case lessthan_circle
    case lessthan_circle_fill
    case lessthan_square
    case lessthan_square_fill
    case greaterthan
    case greaterthan_circle
    case greaterthan_circle_fill
    case greaterthan_square
    case greaterthan_square_fill
    case chevron_left_forwardslash_chevron_right
    case parentheses
    case curlybraces
    case curlybraces_square
    case curlybraces_square_fill
    case ellipsis_curlybraces
    case number
    case number_circle
    case number_circle_fill
    case number_square
    case number_square_fill
    case x_squareroot
    case xmark_circle
    case xmark_circle_fill
    case xmark_square_fill
    case checkmark_circle
    case checkmark_circle_fill
    case checkmark_circle_trianglebadge_exclamationmark
    case checkmark_square_fill
    case checkmark_rectangle
    case checkmark_rectangle_fill
    case checkmark_rectangle_portrait
    case checkmark_rectangle_portrait_fill
    case checkmark_diamond
    case checkmark_diamond_fill
    case checkmark_shield
    case checkmark_shield_fill
    case chevron_left
    case chevron_left_circle
    case chevron_left_circle_fill
    case chevron_left_square
    case chevron_left_square_fill
    case chevron_backward
    case chevron_backward_circle
    case chevron_backward_circle_fill
    case chevron_backward_square
    case chevron_backward_square_fill
    case chevron_right
    case chevron_right_circle
    case chevron_right_circle_fill
    case chevron_right_square
    case chevron_right_square_fill
    case chevron_forward
    case chevron_forward_circle
    case chevron_forward_circle_fill
    case chevron_forward_square
    case chevron_forward_square_fill
    case chevron_left_2
    case chevron_backward_2
    case chevron_right_2
    case chevron_forward_2
    case chevron_up
    case chevron_up_circle
    case chevron_up_circle_fill
    case chevron_up_square
    case chevron_up_square_fill
    case chevron_down
    case chevron_down_circle
    case chevron_down_circle_fill
    case chevron_down_square
    case chevron_down_square_fill
    case chevron_up_chevron_down
    case chevron_compact_up
    case chevron_compact_down
    case chevron_compact_left
    case chevron_compact_right
    case arrow_left_circle
    case arrow_left_circle_fill
    case arrow_left_square
    case arrow_left_square_fill
    case arrow_backward
    case arrow_backward_circle
    case arrow_backward_circle_fill
    case arrow_backward_square
    case arrow_backward_square_fill
    case arrow_right_circle
    case arrow_right_circle_fill
    case arrow_right_square
    case arrow_right_square_fill
    case arrow_forward
    case arrow_forward_circle
    case arrow_forward_circle_fill
    case arrow_forward_square
    case arrow_forward_square_fill
    case arrow_up_circle
    case arrow_up_circle_fill
    case arrow_up_square
    case arrow_up_square_fill
    case arrow_down_circle
    case arrow_down_circle_fill
    case arrow_down_square
    case arrow_down_square_fill
    case arrow_up_left_circle
    case arrow_up_left_circle_fill
    case arrow_up_left_square
    case arrow_up_left_square_fill
    case arrow_up_backward
    case arrow_up_backward_circle
    case arrow_up_backward_circle_fill
    case arrow_up_backward_square
    case arrow_up_backward_square_fill
    case arrow_up_right_circle
    case arrow_up_right_circle_fill
    case arrow_up_right_square
    case arrow_up_right_square_fill
    case arrow_up_forward
    case arrow_up_forward_circle
    case arrow_up_forward_circle_fill
    case arrow_up_forward_square
    case arrow_up_forward_square_fill
    case arrow_down_left_circle
    case arrow_down_left_circle_fill
    case arrow_down_left_square
    case arrow_down_left_square_fill
    case arrow_down_backward
    case arrow_down_backward_circle
    case arrow_down_backward_circle_fill
    case arrow_down_backward_square
    case arrow_down_backward_square_fill
    case arrow_down_right_circle
    case arrow_down_right_circle_fill
    case arrow_down_right_square
    case arrow_down_right_square_fill
    case arrow_down_forward
    case arrow_down_forward_circle
    case arrow_down_forward_circle_fill
    case arrow_down_forward_square
    case arrow_down_forward_square_fill
    case arrow_left_arrow_right
    case arrow_left_arrow_right_circle
    case arrow_left_arrow_right_circle_fill
    case arrow_left_arrow_right_square
    case arrow_left_arrow_right_square_fill
    case arrow_up_arrow_down_circle
    case arrow_up_arrow_down_circle_fill
    case arrow_up_arrow_down_square
    case arrow_up_arrow_down_square_fill
    case arrow_uturn_left
    case arrow_uturn_left_circle
    case arrow_uturn_left_circle_fill
    case arrow_uturn_left_circle_badge_ellipsis
    case arrow_uturn_left_square
    case arrow_uturn_left_square_fill
    case arrow_uturn_backward
    case arrow_uturn_backward_circle
    case arrow_uturn_backward_circle_fill
    case arrow_uturn_backward_circle_badge_ellipsis
    case arrow_uturn_backward_square
    case arrow_uturn_backward_square_fill
    case arrow_uturn_right
    case arrow_uturn_right_circle
    case arrow_uturn_right_circle_fill
    case arrow_uturn_right_square
    case arrow_uturn_right_square_fill
    case arrow_uturn_forward
    case arrow_uturn_forward_circle
    case arrow_uturn_forward_circle_fill
    case arrow_uturn_forward_square
    case arrow_uturn_forward_square_fill
    case arrow_uturn_up
    case arrow_uturn_up_circle
    case arrow_uturn_up_circle_fill
    case arrow_uturn_up_square
    case arrow_uturn_up_square_fill
    case arrow_uturn_down
    case arrow_uturn_down_circle
    case arrow_uturn_down_circle_fill
    case arrow_uturn_down_square
    case arrow_uturn_down_square_fill
    case arrow_up_and_down_and_arrow_left_and_right
    case arrow_up_left_and_down_right_and_arrow_up_right_and_down_left
    case arrow_left_and_right_circle
    case arrow_left_and_right_circle_fill
    case arrow_left_and_right_square
    case arrow_left_and_right_square_fill
    case arrow_up_and_down
    case arrow_up_and_down_circle
    case arrow_up_and_down_circle_fill
    case arrow_up_and_down_square
    case arrow_up_and_down_square_fill
    case arrow_up_to_line_compact
    case arrow_up_to_line_circle
    case arrow_up_to_line_circle_fill
    case arrow_down_to_line_compact
    case arrow_down_to_line_circle
    case arrow_down_to_line_circle_fill
    case arrow_left_to_line
    case arrow_left_to_line_compact
    case arrow_left_to_line_circle
    case arrow_left_to_line_circle_fill
    case arrow_backward_to_line
    case arrow_backward_to_line_circle
    case arrow_backward_to_line_circle_fill
    case arrow_right_to_line
    case arrow_right_to_line_compact
    case arrow_right_to_line_circle
    case arrow_right_to_line_circle_fill
    case arrow_forward_to_line
    case arrow_forward_to_line_circle
    case arrow_forward_to_line_circle_fill
    case arrow_clockwise_circle
    case arrow_clockwise_circle_fill
    case arrow_counterclockwise_circle
    case arrow_counterclockwise_circle_fill
    case arrow_up_left_and_arrow_down_right
    case arrow_up_left_and_arrow_down_right_circle
    case arrow_up_left_and_arrow_down_right_circle_fill
    case arrow_up_backward_and_arrow_down_forward
    case arrow_up_backward_and_arrow_down_forward_circle
    case arrow_up_backward_and_arrow_down_forward_circle_fill
    case arrow_down_right_and_arrow_up_left
    case arrow_down_right_and_arrow_up_left_circle
    case arrow_down_right_and_arrow_up_left_circle_fill
    case arrow_down_forward_and_arrow_up_backward
    case arrow_down_forward_and_arrow_up_backward_circle
    case arrow_down_forward_and_arrow_up_backward_circle_fill
    case return_left
    case return_right
    case arrow_2_squarepath
    case arrow_triangle_2_circlepath
    case arrow_triangle_2_circlepath_circle
    case arrow_triangle_2_circlepath_circle_fill
    case exclamationmark_arrow_triangle_2_circlepath
    case arrow_triangle_capsulepath
    case arrow_3_trianglepath
    case arrow_triangle_turn_up_right_diamond
    case arrow_triangle_turn_up_right_diamond_fill
    case arrow_triangle_turn_up_right_circle
    case arrow_triangle_turn_up_right_circle_fill
    case arrow_triangle_merge
    case arrow_triangle_swap
    case arrow_triangle_branch
    case arrow_triangle_pull
    case arrowtriangle_left_circle
    case arrowtriangle_left_circle_fill
    case arrowtriangle_left_square
    case arrowtriangle_left_square_fill
    case arrowtriangle_backward
    case arrowtriangle_backward_fill
    case arrowtriangle_backward_circle
    case arrowtriangle_backward_circle_fill
    case arrowtriangle_backward_square
    case arrowtriangle_backward_square_fill
    case arrowtriangle_right_circle
    case arrowtriangle_right_circle_fill
    case arrowtriangle_right_square
    case arrowtriangle_right_square_fill
    case arrowtriangle_forward
    case arrowtriangle_forward_fill
    case arrowtriangle_forward_circle
    case arrowtriangle_forward_circle_fill
    case arrowtriangle_forward_square
    case arrowtriangle_forward_square_fill
    case arrowtriangle_up_circle
    case arrowtriangle_up_circle_fill
    case arrowtriangle_up_square
    case arrowtriangle_up_square_fill
    case arrowtriangle_down_circle
    case arrowtriangle_down_circle_fill
    case arrowtriangle_down_square
    case arrowtriangle_down_square_fill
    case slash_circle_fill
    case asterisk
    case asterisk_circle_fill
    case dollarsign_circle
    case dollarsign_circle_fill
    case dollarsign_square
    case dollarsign_square_fill
    case centsign_circle
    case centsign_circle_fill
    case centsign_square
    case centsign_square_fill
    case yensign_circle
    case yensign_circle_fill
    case yensign_square
    case yensign_square_fill
    case sterlingsign_circle
    case sterlingsign_circle_fill
    case sterlingsign_square
    case sterlingsign_square_fill
    case francsign_circle
    case francsign_circle_fill
    case francsign_square
    case francsign_square_fill
    case florinsign_circle
    case florinsign_circle_fill
    case florinsign_square
    case florinsign_square_fill
    case turkishlirasign_circle
    case turkishlirasign_circle_fill
    case turkishlirasign_square
    case turkishlirasign_square_fill
    case rublesign_circle
    case rublesign_circle_fill
    case rublesign_square
    case rublesign_square_fill
    case eurosign_circle
    case eurosign_circle_fill
    case eurosign_square
    case eurosign_square_fill
    case dongsign_circle
    case dongsign_circle_fill
    case dongsign_square
    case dongsign_square_fill
    case indianrupeesign_circle
    case indianrupeesign_circle_fill
    case indianrupeesign_square
    case indianrupeesign_square_fill
    case tengesign_circle
    case tengesign_circle_fill
    case tengesign_square
    case tengesign_square_fill
    case pesetasign_circle
    case pesetasign_circle_fill
    case pesetasign_square
    case pesetasign_square_fill
    case pesosign_circle
    case pesosign_circle_fill
    case pesosign_square
    case pesosign_square_fill
    case kipsign_circle
    case kipsign_circle_fill
    case kipsign_square
    case kipsign_square_fill
    case wonsign_circle
    case wonsign_circle_fill
    case wonsign_square
    case wonsign_square_fill
    case lirasign_circle
    case lirasign_circle_fill
    case lirasign_square
    case lirasign_square_fill
    case australsign_circle
    case australsign_circle_fill
    case australsign_square
    case australsign_square_fill
    case hryvniasign_circle
    case hryvniasign_circle_fill
    case hryvniasign_square
    case hryvniasign_square_fill
    case nairasign_circle
    case nairasign_circle_fill
    case nairasign_square
    case nairasign_square_fill
    case guaranisign_circle
    case guaranisign_circle_fill
    case guaranisign_square
    case guaranisign_square_fill
    case coloncurrencysign_circle
    case coloncurrencysign_circle_fill
    case coloncurrencysign_square
    case coloncurrencysign_square_fill
    case cedisign_circle
    case cedisign_circle_fill
    case cedisign_square
    case cedisign_square_fill
    case cruzeirosign_circle
    case cruzeirosign_circle_fill
    case cruzeirosign_square
    case cruzeirosign_square_fill
    case tugriksign_circle
    case tugriksign_circle_fill
    case tugriksign_square
    case tugriksign_square_fill
    case millsign_circle
    case millsign_circle_fill
    case millsign_square
    case millsign_square_fill
    case shekelsign_circle
    case shekelsign_circle_fill
    case shekelsign_square
    case shekelsign_square_fill
    case manatsign_circle
    case manatsign_circle_fill
    case manatsign_square
    case manatsign_square_fill
    case rupeesign_circle
    case rupeesign_circle_fill
    case rupeesign_square
    case rupeesign_square_fill
    case bahtsign_circle
    case bahtsign_circle_fill
    case bahtsign_square
    case bahtsign_square_fill
    case larisign_circle
    case larisign_circle_fill
    case larisign_square
    case larisign_square_fill
    case bitcoinsign_circle
    case bitcoinsign_circle_fill
    case bitcoinsign_square
    case bitcoinsign_square_fill
    case brazilianrealsign_circle
    case brazilianrealsign_circle_fill
    case brazilianrealsign_square
    case brazilianrealsign_square_fill
    case _0_square
    case _0_square_fill
    case _1_square
    case _1_square_fill
    case _2_square
    case _2_square_fill
    case _3_square
    case _3_square_fill
    case _4_square
    case _4_square_fill
    case _4_alt_circle
    case _4_alt_circle_fill
    case _4_alt_square
    case _4_alt_square_fill
    case _5_square
    case _5_square_fill
    case _6_square
    case _6_square_fill
    case _6_alt_circle
    case _6_alt_circle_fill
    case _6_alt_square
    case _6_alt_square_fill
    case _7_square
    case _7_square_fill
    case _8_square
    case _8_square_fill
    case _9_square
    case _9_square_fill
    case _9_alt_circle
    case _9_alt_circle_fill
    case _9_alt_square
    case _9_alt_square_fill
    case _00_circle
    case _00_circle_fill
    case _00_square
    case _00_square_fill
    case _01_circle
    case _01_circle_fill
    case _01_square
    case _01_square_fill
    case _02_circle
    case _02_circle_fill
    case _02_square
    case _02_square_fill
    case _03_circle
    case _03_circle_fill
    case _03_square
    case _03_square_fill
    case _04_circle
    case _04_circle_fill
    case _04_square
    case _04_square_fill
    case _05_circle
    case _05_circle_fill
    case _05_square
    case _05_square_fill
    case _06_circle
    case _06_circle_fill
    case _06_square
    case _06_square_fill
    case _07_circle
    case _07_circle_fill
    case _07_square
    case _07_square_fill
    case _08_circle
    case _08_circle_fill
    case _08_square
    case _08_square_fill
    case _09_circle
    case _09_circle_fill
    case _09_square
    case _09_square_fill
    case _10_square
    case _10_square_fill
    case _11_square
    case _11_square_fill
    case _12_square
    case _12_square_fill
    case _13_square
    case _13_square_fill
    case _14_square
    case _14_square_fill
    case _15_square
    case _15_square_fill
    case _16_square
    case _16_square_fill
    case _17_square
    case _17_square_fill
    case _18_square
    case _18_square_fill
    case _19_square
    case _19_square_fill
    case _20_square
    case _20_square_fill
    case _21_circle_fill
    case _21_square
    case _21_square_fill
    case _22_circle_fill
    case _22_square
    case _22_square_fill
    case _23_circle_fill
    case _23_square
    case _23_square_fill
    case _24_circle_fill
    case _24_square
    case _24_square_fill
    case _25_circle_fill
    case _25_square
    case _25_square_fill
    case _26_circle_fill
    case _26_square
    case _26_square_fill
    case _27_circle_fill
    case _27_square
    case _27_square_fill
    case _28_circle_fill
    case _28_square
    case _28_square_fill
    case _29_circle_fill
    case _29_square
    case _29_square_fill
    case _30_circle_fill
    case _30_square
    case _30_square_fill
    case _31_circle_fill
    case _31_square
    case _31_square_fill
    case _32_circle_fill
    case _32_square
    case _32_square_fill
    case _33_circle_fill
    case _33_square
    case _33_square_fill
    case _34_circle_fill
    case _34_square
    case _34_square_fill
    case _35_circle_fill
    case _35_square
    case _35_square_fill
    case _36_circle_fill
    case _36_square
    case _36_square_fill
    case _37_circle_fill
    case _37_square
    case _37_square_fill
    case _38_circle_fill
    case _38_square
    case _38_square_fill
    case _39_circle_fill
    case _39_square
    case _39_square_fill
    case _40_circle_fill
    case _40_square
    case _40_square_fill
    case _41_circle_fill
    case _41_square
    case _41_square_fill
    case _42_circle_fill
    case _42_square
    case _42_square_fill
    case _43_circle_fill
    case _43_square
    case _43_square_fill
    case _44_circle_fill
    case _44_square
    case _44_square_fill
    case _45_circle_fill
    case _45_square
    case _45_square_fill
    case _46_circle_fill
    case _46_square
    case _46_square_fill
    case _47_circle_fill
    case _47_square
    case _47_square_fill
    case _48_circle_fill
    case _48_square
    case _48_square_fill
    case _49_circle_fill
    case _49_square
    case _49_square_fill
    case _50_circle_fill
    case _50_square
    case _50_square_fill
    case applelogo
    case placeholdertext_fill
    case z_square_fill
    case y_square_fill
    case x_square_fill
    case w_square_fill
    case v_square_fill
    case u_square_fill
    case t_square_fill
    case s_square_fill
    case r_square_fill
    case q_square_fill
    case p_square_fill
    case o_square_fill
    case n_square_fill
    case m_square_fill
    case l_square_fill
    case k_square_fill
    case j_square_fill
    case i_square_fill
    case h_square_fill
    case g_square_fill
    case f_square_fill
    case d_square_fill
    case c_square_fill
    case b_square_fill
    case a_square_fill
    case z_circle_fill
    case y_circle_fill
    case x_circle_fill
    case w_circle_fill
    case v_circle_fill
    case u_circle_fill
    case t_circle_fill
    case s_circle_fill
    case r_circle_fill
    case q_circle_fill
    case p_circle_fill
    case o_circle_fill
    case n_circle_fill
    case m_circle_fill
    case l_circle_fill
    case k_circle_fill
    case j_circle_fill
    case i_circle_fill
    case h_circle_fill
    case g_circle_fill
    case f_circle_fill
    case e_circle_fill
    case d_circle_fill
    case c_circle_fill
    case b_circle_fill
    case a_circle_fill
    case z_square
    case y_square
    case x_square
    case w_square
    case v_square
    case u_square
    case t_square
    case s_square
    case r_square
    case q_square
    case p_square
    case o_square
    case n_square
    case m_square
    case l_square
    case k_square
    case j_square
    case i_square
    case h_square
    case g_square
    case f_square
    case e_square
    case d_square
    case c_square
    case b_square
    case a_square
    case questionmark_diamond_fill
    case e_square_fill
    case arrow_turn_up_right
    case arrow_turn_up_left
    case arrow_turn_left_down
    case arrow_turn_left_up
    case _50_circle
    case _49_circle
    case _48_circle
    case _47_circle
    case _46_circle
    case _45_circle
    case _44_circle
    case _43_circle
    case _42_circle
    case _41_circle
    case _40_circle
    case _39_circle
    case _38_circle
    case _37_circle
    case _36_circle
    case _35_circle
    case _34_circle
    case _33_circle
    case _32_circle
    case _31_circle
    case _30_circle
    case _29_circle
    case _28_circle
    case _27_circle
    case _26_circle
    case _25_circle
    case _24_circle
    case _23_circle
    case _22_circle
    case _21_circle
    case poweroff
    case hexagon_fill
    case hexagon
    case diamond_bottomhalf_filled
    case diamond_tophalf_filled
    case diamond_righthalf_filled
    case diamond_lefthalf_filled
    case square_bottomhalf_filled
    case square_tophalf_filled
    case arrow_turn_down_right
    case arrow_turn_down_left
    case arrow_turn_right_down
    case arrow_turn_right_up
    case arrow_down_to_line
    case arrow_up_to_line
    case _10_circle_fill
    case _9_circle_fill
    case _8_circle_fill
    case _7_circle_fill
    case _6_circle_fill
    case _5_circle_fill
    case _4_circle_fill
    case _3_circle_fill
    case _2_circle_fill
    case _1_circle_fill
    case snowflake
    case xmark
    case checkmark
    case airplane
    case exclamationmark_triangle
    case die_face_6
    case die_face_5
    case die_face_4
    case die_face_3
    case die_face_2
    case die_face_1
    case suit_club
    case suit_diamond_fill
    case suit_heart_fill
    case suit_spade
    case suit_club_fill
    case suit_diamond
    case suit_heart
    case suit_spade_fill
    case moon_fill
    case peacesign
    case multiply_square
    case xmark_square
    case checkmark_square
    case star
    case star_fill
    case umbrella_fill
    case triangle_righthalf_filled
    case triangle_lefthalf_filled
    case square_righthalf_filled
    case square_lefthalf_filled
    case circle_tophalf_filled
    case circle_bottomhalf_filled
    case circle_righthalf_filled
    case circle_lefthalf_filled
    case circle_fill
    case circle_inset_filled
    case arrowtriangle_left
    case arrowtriangle_left_fill
    case arrowtriangle_down
    case arrowtriangle_down_fill
    case arrowtriangle_right
    case arrowtriangle_right_fill
    case arrowtriangle_up
    case arrowtriangle_up_fill
    case square_fill
    case _0_circle_fill
    case _20_circle_fill
    case _19_circle_fill
    case _18_circle_fill
    case _17_circle_fill
    case _16_circle_fill
    case _15_circle_fill
    case _14_circle_fill
    case _13_circle_fill
    case _12_circle_fill
    case _11_circle_fill
    case _0_circle
    case z_circle
    case y_circle
    case x_circle
    case w_circle
    case v_circle
    case u_circle
    case t_circle
    case s_circle
    case r_circle
    case q_circle
    case p_circle
    case o_circle
    case n_circle
    case m_circle
    case l_circle
    case k_circle
    case j_circle
    case i_circle
    case h_circle
    case g_circle
    case f_circle
    case e_circle
    case d_circle
    case c_circle
    case b_circle
    case a_circle
    case _20_circle
    case _19_circle
    case _18_circle
    case _17_circle
    case _16_circle
    case _15_circle
    case _14_circle
    case _13_circle
    case _12_circle
    case _11_circle
    case _10_circle
    case _9_circle
    case _8_circle
    case _7_circle
    case _6_circle
    case _5_circle
    case _4_circle
    case _3_circle
    case _2_circle
    case _1_circle
    case powersleep
    case poweron
    case togglepower
    case power
    case eject
    case `return`
    case directcurrent
    case escape
    case alt
    case delete_left
    case clear
    case delete_right
    case option
    case command
    case projective
    case control
    case dot_square
    case square_split_diagonal_2x2
    case square_split_1x2
    case square_split_2x2
    case equal_circle
    case asterisk_circle
    case smallcircle_circle
    case smallcircle_filled_circle
    case slash_circle
    case multiply_circle
    case minus_circle
    case plus_circle
    case capslock
    case shift
    case arrow_up_arrow_down
    case arrow_clockwise
    case arrow_counterclockwise
    case arrow_down_left
    case arrow_down_right
    case arrow_up_right
    case arrow_up_left
    case arrow_left_and_right
    case arrow_down
    case arrow_right
    case arrow_up
    case arrow_left
    case triangle
    case square
    case circle
    case paragraphsign

}
